# param metrics
WORD_COUNTER = "WordCounter"
SUBSTRING_COUNTER = "SubstringCounter"
CHAR_COUNTER = "CharCounter"
SPECIFIC_BRANCH_COMMIT_COUNTER = "SpecificBranchCommitCounter"
SPECIFIC_LENGTH_PASTE_COUNTER = "SpecificLengthPasteCounter"
SPECIFIC_LENGTH_COPY_COUNTER = "SpecificLengthCopyCounter"

# non param metrics
MAX_OPENED_PROJECTS = "MaxOpenedProjects"
PROJECT_OPENS_NUMBER = "ProjectOpensNumber"
COMMIT_COUNTER = "CommitCounter"
EDITOR_COUNTER = "EditorCounter"
MAX_OPENED_EDITORS = "MaxOpenedEditors"
COPY_COUNTER = "CopyCounter"
PASTE_COUNTER = "PasteCounter"
COPY_LENGTH_COUNTER = "CopyLengthCounter"
PASTE_LENGTH_COUNTER = "PasteLengthCounter"
MAX_PASTE_LENGTH = "MaxPasteLength"
MAX_COPY_LENGTH = "MaxCopyLength"
TOTAL_TYPED_COUNTER = "TotalTypedCounter"
DELETED_COUNTER = "DeletedCounter"
DELETED_LENGTH_COUNTER = "DeletedLengthCounter"
