# Generated by Django 3.1.7 on 2021-05-06 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='time',
        ),
        migrations.AddField(
            model_name='userstats',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 1, 14, 978947, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='userstats',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 1, 14, 978947, tzinfo=utc)),
        ),
    ]
