# Generated by Django 3.1.7 on 2021-05-06 17:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0002_auto_20210506_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines_written', models.IntegerField(default=0)),
                ('time_from', models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 7, 34, 122282, tzinfo=utc))),
                ('time_to', models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 7, 34, 122282, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
