# Generated by Django 3.1.7 on 2021-05-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210506_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStat',
        ),
    ]
