# Generated by Django 3.1.7 on 2021-05-08 18:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210508_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ref_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 18, 16, 32, 371105, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 18, 16, 32, 371105, tzinfo=utc)),
        ),
    ]
