# Generated by Django 3.1.7 on 2021-05-08 18:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210508_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='employee_key',
            new_name='employer_key',
        ),
        migrations.AlterField(
            model_name='userstat',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 18, 22, 21, 659354, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 18, 22, 21, 659354, tzinfo=utc)),
        ),
    ]
