# Generated by Django 3.1.7 on 2021-06-08 06:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210526_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tracked_metrics',
            field=models.ManyToManyField(blank=True, related_name='metrics', to='users.Metric'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tracked_metrics',
            field=models.ManyToManyField(blank=True, related_name='u_metrics', to='users.Metric'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 6, 40, 2, 440023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 6, 40, 2, 440023, tzinfo=utc)),
        ),
    ]
