# Generated by Django 3.1.7 on 2021-06-08 20:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0033_auto_20210608_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 20, 12, 13, 592923, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 20, 12, 13, 592923, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='FeedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('msg_content', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 6, 8, 20, 12, 13, 598906, tzinfo=utc))),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
