# Generated by Django 3.1.7 on 2021-06-09 16:54

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0034_auto_20210608_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 16, 54, 55, 377549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 16, 54, 55, 371565, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 16, 54, 55, 371565, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('metric_to_goal', models.JSONField(default=dict)),
                ('assigned_users', models.ManyToManyField(related_name='unfinished_achievements', to=settings.AUTH_USER_MODEL)),
                ('completed_users', models.ManyToManyField(blank=True, related_name='finished_achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
