# Generated by Django 3.1.7 on 2021-06-13 15:26

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20210613_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 15, 26, 42, 343421, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='substringcountingmetric',
            name='substring',
            field=models.CharField(max_length=80, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 15, 26, 42, 337405, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 15, 26, 42, 337405, tzinfo=utc)),
        ),
    ]
