# Generated by Django 3.1.7 on 2021-06-13 18:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20210613_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificBranchCommitCounterMetric',
            fields=[
                ('metric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.metric')),
                ('branch_name', models.CharField(max_length=100, unique=True)),
            ],
            bases=('users.metric',),
        ),
        migrations.CreateModel(
            name='SpecificLengthCopyPasteCounter',
            fields=[
                ('metric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.metric')),
                ('substring_length', models.IntegerField(unique=True)),
            ],
            bases=('users.metric',),
        ),
        migrations.AddField(
            model_name='metric',
            name='string_representation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='feedmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 18, 32, 48, 369685, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 18, 32, 48, 345750, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 18, 32, 48, 345750, tzinfo=utc)),
        ),
    ]
