# Generated by Django 3.1.7 on 2021-06-14 22:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20210613_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 22, 55, 36, 774009, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='specificbranchcommitcountermetric',
            name='branch_name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='specificlengthcopypastecounter',
            name='substring_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 22, 55, 36, 756463, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 22, 55, 36, 756463, tzinfo=utc)),
        ),
    ]
